### ISSUE TITLE
Add automatic alerts when any certificates expires within a given threshold

### ISSUE THREAD

**Issue by gettoknowmii** [Icinga/icingaweb2-module-x509#229]
it would great for this module to send alerts as well. Can we add alerting functionality to this module?

**Comment by slalomsk8er** [comment]
Right now the architecture is set up, so that one creates a normal services and as check command, `icingacli` is used to query the state of the certificate in question.

`'/usr/bin/icingacli' 'x509' 'check' 'host' '--critical' '3d' '--host' 'icinga.example.com' '--ip' '10.5.69.77' '--port' '5665' '--warning' '7d'
`
So, it utilizes the normal Icinga2 notifications.

It's also possible to automate the creation of the services with the director module as x509 provides a import source.

Maybe in the future, the planed notification module can directly be utilized form the x509 module to send out alerts without the need to create services.

**Comment by nilmerg** [comment]
I find this question surprising, given the fact that there's [an entire chapter about this in the documentation](https://icinga.com/docs/icinga-certificate-monitoring/latest/doc/10-Monitoring/) explaining thoroughly how it works.

Anyway, thank you Dominik!
