### ISSUE TITLE
Letsencrypt chain is not valid

### ISSUE THREAD

**Issue by manny4566** [Icinga/icingaweb2-module-x509#231]
## Describe the bug
My Let's Encrypt certificates are still invalid, because the module is "unable to get issuer certificate."
I have importet the 2 certificats with "icingacli x509 import" and they are both marked as "is trusted".

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Create a Let's Encrypt certificate
2. Scan the host
3. Import the Ca Chain

## Expected behavior
Fix the problem and make Let's Encrypt certificates as valid

## Screenshots
![grafik](https://github.com/Icinga/icingaweb2-module-x509/assets/23473485/9e01d825-c5c8-45f4-8901-6056316cdd40)

![grafik](https://github.com/Icinga/icingaweb2-module-x509/assets/23473485/bbdc73cc-12bd-4b3c-9d85-fc090999b201)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.12.1; x509 -> v1.3.2
* Web browser used:  Firefox / Chrome
* Icinga 2 version used (`icinga2 --version`): r2.14.1-1
* PHP version used (`php --version`): PHP 8.2.7
* Server operating system and version: Debian 12

**Comment by yhabteab** [comment]
Hi @manny4566, thanks for reporting!

> I have importet the 2 certificats with "icingacli x509 import" and they are both marked as "is trusted".

Which `ISRG Root X1` certificate have you imported? According to [`crt.sh`] (https://crt.sh/?caid=7394), there are two certificates. 
<img width="1276" alt="Bildschirmfoto 2024-01-15 um 12 44 43" src="https://github.com/Icinga/icingaweb2-module-x509/assets/57616252/1d123011-5a6a-4d8f-b1eb-a44cc2e64376">

Looking at your screenshot, it looks like you have imported the second one, which is signed by another top-level CA (`DST Root CA X3`) that is not marked as trusted, I guess.

> ![grafik](https://private-user-images.githubusercontent.com/23473485/295036629-bbdc73cc-12bd-4b3c-9d85-fc090999b201.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTIwMTksIm5iZiI6MTcwNTMxMTcxOSwicGF0aCI6Ii8yMzQ3MzQ4NS8yOTUwMzY2MjktYmJkYzczY2MtMTJiZC00YjNjLTlkODUtZmMwOTA5OTliMjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5NDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjM2UxMzcwZjY3NmQ1NjY3M2RhZDE0MWU0N2ZjZTkwNDI1MzU3MDZjMGQwZTczNWMxNTk1ODkxMDkzMTAyNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dXb2SmanFeaiuv4TE7If5aDfynSOkraQSkqraU0ev-k)

You have to either manually import the `DST Root CA X3` certificate or use the self-signed version of `ISRG Root X1` (the first certificate), otherwise x509 won't be able to determine the self-signed CA.

**Comment by yhabteab** [comment]
Didn't get any reaction for over a week, so I assume you've already solved it. So I'm closing it!

**Comment by manny4566** [comment]
Thank you. I have changed it and in works now.
