### ISSUE TITLE
Monitoring Certs via satellite

### ISSUE THREAD

**Issue by meyju** [Icinga/icingaweb2-module-x509#34]
Hi, 

I have a icinga setup with satellites in seperated networks. Is it possible to check certificates wich ware only accessable within a specific network?

For me it looks that only the icinga master executes the checks.

Regards
Julian

**Comment by starwars108** [comment]
In my opinion it's not the icinga master that execute the checks - it's the icingaweb2 host. I know it's often the same.

But I agree - it would be great if there is any distributed solution based on the satellite structure!

**Comment by nilmerg** [comment]
Hi,

Icinga itself only performs checks in order to monitor something known. This module however does the very opposite as it scans networks and collects certificates which can then be monitored. So the only integration with Icinga would be to monitor such by using a separate check command. (See #16 for this) That's where any relation to Icinga and its distributed nature ends. (At least in my point of view)

So the solution for this issue would be installing the module in the isolated network and have it either:

a) speak to a remote database outside of the current network (the same database that is connected to the web interface)
b) maintain its own database and consider this another part of the network that needs to be maintained/monitored

For this to work it's (*should be*) enough to install `icingacli` and the module on a host in the isolated network.

Are these viable solutions for you?

**Comment by nilmerg** [comment]
I consider this solved now. If any of you think different please re-open.

**Comment by widhalmt** [comment]
@nilmerg Using the module from a centralised position (aka your Icinga Web 2 instance) to scan different networks which are not directly accessible should definitely be possible.

Installing a full blown Icinga Web 2 just to run this module seems a bit over the top especially because you don't want to have Web in many different locations in the most situations. Think administration overhead, security etc.

Having the module offer a way of communication via an Icinga 2 satellite might not be at thing that's technically natural but it could help with making the administration part a lot easier. Just think about firewall rules, policies etc. For me it doesn't have to be part of the cluster protocoll but having a way of forwarding the request over a satellite service would be much appreciated in any way which is technically doable.

In my special case I'm working with a customer who has itself lots of customers which all get monitoring as a service from them. They can't have more than Icinga satellites in the customers networks and they sometimes have the same subnet numbers in different customers networks.

**Comment by widhalmt** [comment]
ref/NC/631617

**Comment by nilmerg** [comment]
> For this to work it's (should be) enough to install icingacli and the module on a host in the isolated network.

It's just the module and `icingacli`, not a full blown web instance. Sure, you'll have to setup a route etc. to the database so the results are stored somewhere.

**Comment by mkayontour** [comment]
I need to append something to @widhalmt comment. 

We need indeed any possibility to forward the informations into the parent zone somehow. I'm thinking of security zones which we only get the Icinga port for communication and also only in one direction. We don't get any permissions to open the port to the database outside of the security zone.

**Comment by jwhite-ac** [comment]
Having the ability to use this module via the satellites (without the need for a custom setup and paths to the database, ie just via the standard clustering methods - satellites forward data to their parent zones) would be extremely useful. As it stands where I work, this module isn't going to work for us as we have network segregation with multiple DMZs and internal networks, which we cannot give complete access to the Icinga2 masters. Having the satellites scan for cert data and forward to the master would make this module infinitely more useful in the wild :)
