### ISSUE TITLE
Without any schedule, the systemd service immediately enters failed state

### ISSUE THREAD

**Issue by pdorschner** [Icinga/icingaweb2-module-x509#35]
## Expected Behavior
Initialization of the systemd service first, without a scheduletime in jobs set, should reload the systemd service.

## Current Behavior
Initialization of the systemd service first, without a scheduletime in jobs set, do not reload the service. It just exits immediately.

## Possible Solution
If there's no schedule in the job set and if you want a systemd service, there should be a warning to restart/reload the service or the schedule field should be mandatory. 

## Steps to Reproduce (for bugs)

1. Create a job without a schedule 
2. Set up the systemd service
3. Execute the command: icingacli x509 jobs run

## Context
At the first time i created a job without a schedule, because there was no mandatory field (just to test the module). Afterwards I made the systemd service and enabled it. I thought the service reload if I set up a schedule in the jobs.

## Your Environment

* Module version (System - About): 1.0.0
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): v2.10.2-160-g1c772aa
* Operating System and version: Centos7 
* Webserver, PHP versions:

**Comment by nilmerg** [comment]
Without any schedule the service immediately enters failed state:

```
● icinga-x509.service - Icinga Web 2 X.509 Module Jobs Runner
   Loaded: loaded (/etc/systemd/system/icinga-x509.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Fr 2019-03-22 10:03:37 UTC; 5s ago
  Process: 6387 ExecStart=/usr/bin/icingacli x509 jobs run (code=exited, status=0/SUCCESS)
 Main PID: 6387 (code=exited, status=0/SUCCESS)

Mär 22 10:03:37 localhost.localdomain systemd[1]: icinga-x509.service holdoff time over, scheduling restart.
Mär 22 10:03:37 localhost.localdomain systemd[1]: Stopped Icinga Web 2 X.509 Module Jobs Runner.
Mär 22 10:03:37 localhost.localdomain systemd[1]: start request repeated too quickly for icinga-x509.service
Mär 22 10:03:37 localhost.localdomain systemd[1]: Failed to start Icinga Web 2 X.509 Module Jobs Runner.
Mär 22 10:03:37 localhost.localdomain systemd[1]: Unit icinga-x509.service entered failed state.
Mär 22 10:03:37 localhost.localdomain systemd[1]: icinga-x509.service failed.
```

It's then never restarted automatically. Even if it's able to launch it won't recognize any new jobs or updated schedules.

This may be solved the following ways:

a) Reload the configuration from disks each time a job is run
b) Reload the configuration from disk once a signal comes in (i.e. proper reload procedures)
c) Let systemd handle the restart in case specific files change

For a) and b) to work the command must not exit just because there are no schedules available. b) additionally requires a mechanism to initiate the reload. c) however may only require proper SIGTERM handling in the process. (May already be the case, didn't test)

d) Or all of this is too much hassle and we just let the user handle restarts. (But issue a warning in case something changed)

**Comment by mwaldmueller** [comment]
+1
